### PR TITLE
[2] - create_did method working

### PR DESCRIPTION
**Pull request by hardiksharma11**
- Created the create_did function along with several other required functions.
- Added custom-types.json. Reason for that being py-substrate-interface currently does not have runtime calls in its metadata. therfore I had to write didApi and its calls manually in it and use it.

### CODE REVIEW

**Review by vatsa287 — DISMISSED** [review]
Please rebase and amend the commit.

**Comment by hardiksharma11** [comment]
@vatsa287 @adi-a11y  PTAL. 
Also closes #5

**Review by belyrs — DISMISSED** [review]

**Comment by belyrs** [comment]
@hardiksharma11 
Commit with `-s`. So the commit is signed and verified with your ID.

**Comment by hardiksharma11** [comment]
@adi-a11y  PTAL

**Review by belyrs — APPROVED** [review]

**Review by belyrs — CHANGES_REQUESTED** [review]
All the commits should be signed. Not just one.

**Comment by vatsa287** [comment]
@hardiksharma11 I will force push for now. You can open separate PRs for every commit from now on.

**Comment by hardiksharma11** [comment]
> All the commits should be signed. Not just one.

I'll keep that in mind from next time

**Pull request merged**
