### PR TITLE
[2] - Basic setup and config, identifier 

### PR DESCRIPTION
**Pull request by hardiksharma11**
Did the following tasks
- Setup of the app
- Written config module
- Written identifier module along with SDKErrors and constants
- Chain in network module pallet

### CODE REVIEW

**Comment by hardiksharma11** [comment]
Added demo script for connection. Now working for network members

**Comment by DharmikPansuriya** [comment]
Hey @hardiksharma11, Just checked PR. 

I have following suggestions:
1. Can we maintain all the requirements in a single file instead of three different files? This approach would reduce redundancy and minimize the risk of discrepancies between files. 
> For example, the package substrate-interface is currently listed in:
>> a. requirements.txt
>> b. setup.py
>> c. cord.py.egg-info/dependency_links.txt (This seems runtime generated, then we can ignore?)

2. Instead of using print statements, can we switch to using a logging framework? 
> This change will help maintain logs more effectively, whether they are stored locally or streamed to the cloud, such as GCP.

Let me know your opinion @hardiksharma11 @vatsa287!

**Comment by hardiksharma11** [comment]
Thanks for the suggestions, here are the changes that could be made
1. We will keep only the `setup.py` file for requirements as well as to maintain package structure of cord.py
2. `logging` module in python could be used as a logging framework which would also help the developer to categorize statements as debug, warning or info.

**Comment by vatsa287** [comment]
LGTM

**Review by belyrs — APPROVED** [review]
LGTM

**Review by vatsa287 — APPROVED** [review]
Please rebase for second PR.

**Pull request merged**
